Repository taehong0-0/Ucluverse, pull requests merged in 2022-04, with the labels that each got.

#42 Feat/#41 : 파일 업로드
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/user/dto/create-user.dto.ts
  server/src/user/entities/profilePhoto.entity.ts
  server/src/user/entities/user.entity.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: BE, Feat

#45 Refactor/#43 : aws S3 파일 업로드
  server/package-lock.json
  server/package.json
  server/src/config/awsS3config.ts
  server/src/config/validationSchema.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: BE, Refactor

#46 Feat/#33 - 활동사진 UI 슬라이드 구현
  client/package-lock.json
  client/package.json
  client/src/Assets/left-arrow.png
  client/src/Assets/right-arrow.png
  client/src/Assets/test1.jpeg
  client/src/Assets/test2.jpeg
  client/src/Assets/test3.jpeg
  client/src/Assets/test4.jpeg
  client/src/Assets/test5.jpeg
  client/src/Assets/활동사진.png
  client/src/Components/Main/MainActivity/MainActivity.tsx
  client/src/Components/Main/MainActivity/style.ts
  client/src/Pages/Main/Main.tsx
  client/src/index.tsx
Labels: FE, Feat

#50 Feat/#47 - 수상내역 UI 뼈대 추가
  client/src/Assets/수상내역.png
  client/src/Components/Main/MainAward/MainAward.tsx
  client/src/Components/Main/MainAward/style.ts
  client/src/Pages/Main/Main.tsx
Labels: FE, Feat

#51 Feat/#48 - 신설동아리 UI 추가
  client/src/Assets/신설 동아리.png
  client/src/Components/Main/MainNewClub/MainNewClub.tsx
  client/src/Components/Main/MainNewClub/style.ts
  client/src/Pages/Main/Main.tsx
Labels: FE, Feat

#54 Feat/#33 Style - 슬라이드 css 수정
  client/src/Components/Main/MainActivity/MainActivity.tsx
  client/src/Components/Main/MainActivity/style.ts
Labels: FE, Feat

#55 Feat/#49 - 활동우수동아리 컴포넌트 구현
  client/src/Assets/활동 우수 동아리.png
  client/src/Components/Main/MainGreatClub/MainGreatClub.tsx
  client/src/Components/Main/MainGreatClub/style.ts
  client/src/Pages/Main/Main.tsx
Labels: FE, Feat

#65 Feat/#59 - 동아리 페이지 메인 UI 구현
  client/src/App.tsx
  client/src/Components/Club/Board/ClubBoard.tsx
  client/src/Components/Club/Board/style.ts
  client/src/Components/Club/Header/ClubHeader.tsx
  client/src/Components/Club/Header/style.ts
  client/src/Components/Club/Main/ClubMain.tsx
  client/src/Components/Club/Main/style.ts
  client/src/Components/Club/SideBar/ClubSideBar.tsx
  client/src/Components/Club/SideBar/style.ts
  client/src/Components/Header/style.ts
  client/src/Pages/Club/Club.tsx
Labels: FE, Feat

#69 Feat/#68 : 엔티티 구현 및 연관관계 맵핑
  server/src/app.module.ts
  server/src/clubs/entities/club.entity.ts
  server/src/posters/entities/poster.entity.ts
  server/src/posters/posters.module.ts
  server/src/postings/entities/posting.entity.ts
  server/src/user/entities/user.entity.ts
Labels: BE, Feat

#72 Feat/#70 : 게시글 등록 API
  server/src/clubs/entities/club.entity.ts
  server/src/main.ts
  server/src/postings/dto/create-posting.dto.ts
  server/src/postings/dto/postings-response.dto.ts
  server/src/postings/postings.controller.ts
  server/src/postings/postings.module.ts
  server/src/postings/postings.service.ts
  server/src/user/dto/create-user.dto.ts
Labels: BE, Feat

#98 Feat/#96 : 로그인 방식 수정에 따른 API 수정
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
Labels: BE, Fix, Refactor

#99 Feat/#60 : 로그인 컴포넌트 수정
  client/src/Components/Login/LoginMain.tsx
  client/src/Pages/Login/Login.tsx
  client/src/Routes/AuthRoute.tsx
Labels: Bug, FE, Feat

#101 Feat/#100 : 로그인 방식 수정에 따른 API 수정
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
Labels: BE, Fix, Refactor

#103 Feat/#7 - 로그인 추가
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/Components/Login/LoginInfoMain.tsx
  client/src/Components/Login/LoginMain.tsx
  client/src/Components/Login/style.ts
  client/src/Pages/Login/Login.tsx
Labels: FE, Feat

#108 Feat/#91 : 게시물 수정/삭제 API
  server/src/postings/dto/update-posting.dto.ts
  server/src/postings/postings.controller.ts
  server/src/postings/postings.service.ts
Labels: BE, Feat

#110 Refactor/#109 : 회원가입 로직 수정
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: BE, Refactor

#113 Feat/#111 : 유저 정보 수정 API
  server/package-lock.json
  server/src/app.module.ts
  server/src/user/dto/update-user.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: BE, Feat

#114 Feat/#47 - 수상정보 수정
  client/src/Assets/수상내역.png
  client/src/Components/Main/MainAward/MainAward.tsx
  client/src/Components/Main/MainAward/style.ts
  client/src/Components/Main/MainNewClub/style.ts
Labels: FE, Feat

#115 Feat/#7 - 로그인 수정
  client/package-lock.json
  client/package.json
  client/src/Components/Login/LoginInfoMain.tsx
  client/src/Components/Login/LoginMain.tsx
Labels: FE, Feat

#118 Refactor/#117 : 동아리 로고 저장경로 컬럼 추가
  server/src/clubs/entities/club.entity.ts
Labels: BE, Refactor

#119 Feat/#60 동아리 페이지 수정
  client/src/Components/Club/Board/ActivityBoard/ActivityBoard.tsx
  client/src/Components/Club/Board/ActivityBoard/style.ts
  client/src/Components/Club/Board/ClubBoard.tsx
  client/src/Components/Club/Board/InfoBoard/InfoBoard.tsx
  client/src/Components/Club/Board/InfoBoard/style.ts
  client/src/Components/Club/Board/PostBoard/PostBoard.tsx
  client/src/Components/Club/Board/PostBoard/style.ts
  client/src/Components/Club/Board/style.ts
  client/src/Components/Club/SideBar/ClubSideBar.tsx
  client/src/Components/Club/SideBar/style.ts
  client/src/Components/Login/LoginInfoMain.tsx
  client/src/Components/Login/LoginMain.tsx
  client/src/Components/Post/style.ts
  client/src/Pages/Club/Club.tsx
Labels: FE, Feat

#121 Feat/#40 : Editor UI 추가
  client/package-lock.json
  client/package.json
  client/src/Components/Editor/Editor.tsx
  client/src/Components/Editor/typings.d.ts
  client/src/Pages/Main/Main.tsx
Labels: FE, Feat

#123 Feat/#122 - 동아리 페이지 게시글 작성 추가
  client/src/Components/Button/Button.tsx
  client/src/Components/Button/style.ts
  client/src/Components/Club/Board/ActivityBoard/ActivityBoard.tsx
  client/src/Components/Club/Board/ClubBoard.tsx
  client/src/Components/Club/Board/PostBoard/PostBoard.tsx
  client/src/Components/Club/Board/PostBoard/style.ts
  client/src/Components/Club/Post/ClubPost.tsx
  client/src/Components/Club/Post/Comment/PostComment.tsx
  client/src/Components/Club/Post/Comment/style.ts
  client/src/Components/Club/Post/Header/PostHeader.tsx
  client/src/Components/Club/Post/Header/style.ts
  client/src/Components/Club/Post/Main/PostMain.tsx
  client/src/Components/Club/Post/Main/style.ts
  client/src/Components/Club/Post/Title/PostTitle.tsx
  client/src/Components/Club/Post/Title/style.ts
  client/src/Components/Club/Post/style.ts
  client/src/Components/Club/Posting/Posting.tsx
  client/src/Components/Club/Posting/style.ts
  client/src/Components/Club/SideBar/ClubSideBar.tsx
  client/src/Components/Editor/Editor.tsx
  client/src/Pages/Club/Club.tsx
  client/src/Pages/Main/Main.tsx
Labels: FE, Feat

#127 Refactor/#126 : 파일 저장 기능 클라이언트 측으로 이전함에 따른 회원가입, 회원 정보 수정 API 리팩토링
  server/package-lock.json
  server/src/user/dto/create-user.dto.ts
  server/src/user/dto/update-user.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: BE, Refactor
