Repository taehong0-0/Ucluverse, pull requests merged in 2022-05, with the labels that each got.

#131 Feat/#122 - 게시글 작성 추가
  client/package-lock.json
  client/package.json
  client/src/Components/Club/Posting/Posting.tsx
Labels: FE, Feat

#132 Style/#130 스타일 수정
  .github/workflows/aws.yml
  client/package-lock.json
  client/src/Assets/메인헤더.png
  client/src/Assets/메인헤더글.svg
  client/src/Components/Button/style.ts
  client/src/Components/Club/Board/InfoBoard/style.ts
  client/src/Components/Club/Board/PostBoard/style.ts
  client/src/Components/Club/Board/style.ts
  client/src/Components/Club/Header/style.ts
  client/src/Components/Club/Main/style.ts
  client/src/Components/Club/Post/Header/PostHeader.tsx
  client/src/Components/Club/Post/Header/style.ts
  client/src/Components/Club/Post/Main/style.ts
  client/src/Components/Club/Post/Title/style.ts
  client/src/Components/Club/Post/style.ts
  client/src/Components/Club/Posting/style.ts
  client/src/Components/Club/SideBar/style.ts
  client/src/Components/Editor/Editor.tsx
  client/src/Components/Header/style.ts
  client/src/Components/Input/style.ts
  client/src/Components/Login/LoginInfoMain.tsx
  client/src/Components/Login/LoginMain.tsx
  client/src/Components/Login/style.ts
  client/src/Components/Main/MainActivity/style.ts
  client/src/Components/Main/MainAward/style.ts
  client/src/Components/Main/MainBoard/style.ts
  client/src/Components/Main/MainGreatClub/style.ts
  client/src/Components/Main/MainHeader/style.ts
  client/src/Components/Main/MainNewClub/style.ts
  server/package-lock.json
Labels: FE, Feat

#133 Style/#130 : 헤더 위치 수정
  client/src/Components/Main/MainHeader/style.ts
Labels: FE, Feat

#134 Style/#130 : 이미지 사이즈 수정
  client/src/Components/Login/LoginInfoMain.tsx
  client/src/Components/Login/LoginMain.tsx
Labels: FE, Feat

#142 Feat/#138
  client/src/App.tsx
  client/src/Components/ClubList/ClubBody/ClubBody.tsx
  client/src/Components/ClubList/ClubBody/style.ts
  client/src/Components/ClubList/ClubCategory/ClubCategory.tsx
  client/src/Components/ClubList/ClubCategory/style.ts
  client/src/Components/ClubList/ClubList/ClubList.tsx
  client/src/Components/ClubList/ClubList/style.ts
  client/src/Components/Header/Header.tsx
  client/src/Components/Header/style.ts
  client/src/Components/Login/LoginMain.tsx
  client/src/Pages/Club/ClubList.tsx
Labels: FE, Feat

#144 Feat/#138 : 동아리 리스트 컴포넌트 추가
  client/src/App.tsx
  client/src/Components/ClubList/ClubBody/ClubBody.tsx
  client/src/Components/ClubList/ClubList/ClubList.tsx
  client/src/Components/ClubList/ClubList/style.ts
  client/src/Pages/Club/Club.tsx
Labels: FE, Feat

#145 Feat/#135 : 수상내역 애니메이션 추가
  client/src/Components/Main/MainAward/MainAward.tsx
  client/src/Components/Main/MainAward/style.ts
Labels: FE, Feat

#146 Refactor/#136
  client/package-lock.json
  server/src/auth/auth.module.ts
  server/src/auth/google.strategy.ts
  server/src/config/validationSchema.ts
  server/src/postings/dto/create-posting.dto.ts
  server/src/postings/dto/update-posting.dto.ts
  server/src/postings/entities/posting.entity.ts
  server/src/postings/postings.controller.ts
  server/src/postings/postings.service.ts
Labels: BE, Refactor

#151 Etc/#148 : Swagger 세팅 및 불필요 파일 및 설정 삭제
  server/package-lock.json
  server/package.json
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/google-auth.guard.ts
  server/src/auth/google.strategy.ts
  server/src/config/awsS3config.ts
  server/src/main.ts
  server/src/posters/posters.module.ts
  server/src/postings/dto/create-posting.dto.ts
  server/src/postings/dto/update-posting.dto.ts
  server/src/postings/postings.controller.ts
  server/src/postings/postings.module.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/dto/update-user.dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: BE, Refactor, Etc

#154 Refactor/#152 : 게시물 공개여부/댓글가능여부 포함
  server/src/app.module.ts
  server/src/postings/dto/create-posting.dto.ts
  server/src/postings/dto/update-posting.dto.ts
  server/src/postings/entities/posting.entity.ts
  server/src/postings/postings.controller.ts
  server/src/postings/postings.service.ts
Labels: BE, Refactor, Etc

#156 Feat/#7 : 로그인 로직 수정
  client/src/App.tsx
  client/src/Assets/Footer.png
  client/src/Assets/logout.png
  client/src/Assets/내정보.png
  client/src/Assets/띠배너.png
  client/src/Assets/알림.png
  client/src/Components/ClubList/ClubList/ClubList.tsx
  client/src/Components/Header/Header.tsx
  client/src/Components/Header/style.ts
  client/src/Components/Login/LoginInfoMain.tsx
  client/src/Components/Login/LoginMain.tsx
  client/src/Components/Main/MainAward/MainAward.tsx
  client/src/Hooks/useCheckLogin.ts
  client/src/Pages/Main/Main.tsx
  client/src/Recoil/user.ts
  client/src/Routes/AuthRoute.tsx
  client/src/Routes/LoginRoute.tsx
  client/src/Types/ClubType.ts
  client/src/Types/UserType.ts
Labels: FE, Feat

#158 Etc : url 변경
  client/src/Hooks/useCheckLogin.ts
Labels: FE, Etc

#159 Feat/#138 - 동아리 목록 페이지
  client/src/App.tsx
  client/src/Assets/Character-hello.png
  client/src/Components/ClubList/Body/ClubBody.tsx
  client/src/Components/ClubList/Body/DepartmentClubBody.tsx
  client/src/Components/ClubList/Body/style.ts
  client/src/Components/ClubList/Category/ClubCategory.tsx
  client/src/Components/ClubList/Category/style.ts
  client/src/Components/ClubList/ClubBody/ClubBody.tsx
  client/src/Components/ClubList/ClubList/ClubList.tsx
  client/src/Components/ClubList/ClubList/style.ts
  client/src/Components/Header/Header.tsx
  client/src/Components/Main/MainAward/MainAward.tsx
  client/src/Components/Main/MainGreatClub/style.ts
  client/src/Hooks/useCheckLogin.ts
  client/src/Pages/Club/Club.tsx
  client/src/Pages/Club/ClubList.tsx
  client/src/Pages/Main/Main.tsx
  client/src/Routes/AuthRoute.tsx
  client/src/Routes/LoginRoute.tsx
Labels: FE, Feat

#162 Feat/#135 - 메인페이지 애니메이션 추가
  client/src/Components/Main/MainGreatClub/MainGreatClub.tsx
  client/src/Components/Main/MainGreatClub/style.ts
  client/src/Components/Main/MainNewClub/MainNewClub.tsx
  client/src/Components/Main/MainNewClub/style.ts
Labels: FE, Feat

#163 Feat/#135
  client/src/App.tsx
  client/src/Components/Header/Header.tsx
  client/src/Components/Login/LoginMain.tsx
  client/src/Components/Main/MainGreatClub/style.ts
  client/src/Hooks/useCheckLogin.ts
  client/src/Pages/Main/Main.tsx
  client/src/Recoil/User.ts
  client/src/Routes/AuthRoute.tsx
  client/src/Routes/LoginRoute.tsx
Labels: FE, Feat

#165 Feat/#7 : 로그인 헤더 수정 및 info 수정
  client/src/Components/Header/Header.tsx
  client/src/Components/Login/LoginInfoMain.tsx
Labels: FE, Feat

#166 Feat/#160 - 수상내역 페이지 수정
  client/src/App.tsx
  client/src/Components/Button/Button.tsx
  client/src/Components/Button/style.ts
  client/src/Components/Club/Board/AwardBoard/AwardBoard.tsx
  client/src/Components/Club/Board/AwardBoard/style.ts
  client/src/Components/Club/Board/ClubBoard.tsx
  client/src/Components/Club/Board/PostBoard/PostBoard.tsx
  client/src/Components/Club/Board/PostBoard/style.ts
  client/src/Components/Club/Board/style.ts
  client/src/Components/Club/Posting/Posting.tsx
  client/src/Components/Input/Input.tsx
  client/src/Components/Input/style.ts
  client/src/Components/Login/LoginInfoMain.tsx
  client/src/Pages/Club/Club.tsx
  client/src/Pages/Login/Login.tsx
Labels: FE, Feat

#171 Feat/#7 : 로그인 인포 입력 페이지 수정
  client/package-lock.json
  client/package.json
  client/src/Components/Login/LoginInfoMain.tsx
  client/src/Components/Login/style.ts
  client/src/Util/constant.ts
Labels: FE, Feat

#173 Feat/#172 : 수상내역 리스트 추가
  client/src/Components/Club/Board/AwardBoard/AwardBoard.tsx
  client/src/Components/Club/Board/AwardBoard/style.ts
  client/src/Components/Club/Board/style.ts
Labels: FE, Feat

#177 Feat/#176 - 로그인 정보 페이지 수정
  client/src/Components/Login/LoginInfoMain.tsx
  client/src/Components/Login/style.ts
Labels: FE, Feat

#183 Feat/#182 : 소학회 불러오기 API 구현
  server/src/clubs/clubs.controller.ts
  server/src/clubs/clubs.service.ts
  server/src/clubs/dto/club-respones.dto.ts
Labels: BE, Feat

#193 Feat/#188
  client/src/App.tsx
  client/src/Components/Admin/ClubAdmin/Enrollment/EnrollmentForm.tsx
  client/src/Components/Admin/ClubAdmin/Enrollment/EnrollmentList.tsx
  client/src/Components/Admin/ClubAdmin/Enrollment/style.ts
  client/src/Components/Admin/ClubAdmin/Main/Main.tsx
  client/src/Components/Admin/ClubAdmin/Main/style.ts
  client/src/Components/Admin/ClubAdmin/Member/Member.tsx
  client/src/Components/Admin/ClubAdmin/Member/style.ts
  client/src/Components/Admin/ClubAdmin/Navigation/Navigation.tsx
  client/src/Components/Admin/ClubAdmin/Navigation/style.ts
  client/src/Components/Club/Board/ActivityBoard/ActivityBoard.tsx
  client/src/Components/Club/Board/ActivityBoard/style.ts
  client/src/Components/Club/Board/AwardBoard/AwardBoard.tsx
  client/src/Components/Club/Board/AwardBoard/style.ts
  client/src/Components/Club/Board/ClubBoard.tsx
  client/src/Components/Club/Board/InfoBoard/InfoBoard.tsx
  client/src/Components/Club/Board/PostBoard/PostBoard.tsx
  client/src/Components/Club/Board/PostBoard/style.ts
  client/src/Components/Club/Header/ClubHeader.tsx
  client/src/Components/Club/Header/style.ts
  client/src/Components/Club/Posting/Posting.tsx
  client/src/Components/Club/Posting/style.ts
  client/src/Components/Club/SideBar/ClubSideBar.tsx
  client/src/Components/Club/SideBar/style.ts
  client/src/Components/ClubList/Body/ClubBody.tsx
  client/src/Components/ClubList/Body/DepartmentClubBody.tsx
  client/src/Components/ClubList/ClubList/ClubList.tsx
  client/src/Components/ClubList/ClubList/style.ts
  client/src/Components/DropZone/DropZone.tsx
  client/src/Components/Main/MainActivity/MainActivity.tsx
  client/src/Components/Main/MainAward/MainAward.tsx
  client/src/Components/Main/MainBoard/MainBoardContainer.tsx
  client/src/Components/Main/MainGreatClub/MainGreatClub.tsx
  client/src/Pages/Admin/ClubAdmin.tsx
  client/src/Pages/Club/Club.tsx
  client/src/Recoil/Club.ts
  client/src/Types/ClubType.ts
  client/src/Types/PostType.ts
  client/src/Types/UserType.ts
Labels: FE, Feat

#196 게시글 api 수정
  client/src/Components/Club/Board/AwardBoard/AwardBoard.tsx
  client/src/Components/Club/Board/ClubBoard.tsx
  client/src/Components/Club/Board/PostBoard/PostBoard.tsx
  client/src/Pages/Club/Club.tsx
Labels: FE, Feat

#197 Feat/#155 : 동아리 신청 폼 CRD
  server/src/clubs/entities/club.entity.ts
  server/src/forms/dto/create-form.dto.ts
  server/src/forms/dto/response-form.dto.ts
  server/src/forms/dto/update-form.dto.ts
  server/src/forms/entity/form.entity.ts
  server/src/forms/forms.controller.ts
  server/src/forms/forms.module.ts
  server/src/forms/forms.service.ts
  server/src/postings/postings.controller.ts
  server/src/user/entities/user.entity.ts
  server/src/user/user.service.ts
Labels: BE, Feat

#201 Feat/#175 - 검색창 구현
  client/.prettierrc
  client/src/App.tsx
  client/src/Components/ClubList/Body/ClubBody.tsx
  client/src/Components/ClubList/Body/DepartmentClubBody.tsx
  client/src/Components/Main/MainHeader/SearchBar.tsx
  client/src/Components/Main/MainHeader/style.ts
Labels: FE, Feat

#203 Feat/#202 : 내정보 페이지
  client/src/App.tsx
  client/src/Assets/MainBG.svg
  client/src/Assets/heart.png
  client/src/Assets/people.png
  client/src/Assets/sample-bg-selected.png
  client/src/Assets/sample-bg.png
  client/src/Components/Header/Header.tsx
  client/src/Components/MyPage/MyClub/MyClub.tsx
  client/src/Components/MyPage/MyClub/style.ts
  client/src/Components/MyPage/MyInfo/MyInfo.tsx
  client/src/Components/MyPage/MyInfo/style.ts
  client/src/Pages/Main/Main.tsx
  client/src/Pages/MyPage/MyPage.tsx
Labels: FE, Feat

#212 Refactor/#208 : 신청 양식 생성, 수정 API 변경
  server/src/postings/dto/postings-response.dto.ts
  server/src/postings/postings.controller.ts
  server/src/postings/postings.service.ts
Labels: BE, Refactor

#218 Feat/#179
  client/src/App.tsx
  client/src/Components/Admin/ClubAdmin/Enrollment/EnrollmentForm.tsx
  client/src/Components/Admin/ClubAdmin/Enrollment/EnrollmentList.tsx
  client/src/Components/Admin/ClubAdmin/Enrollment/style.ts
  client/src/Components/Admin/ClubAdmin/Main/Main.tsx
  client/src/Components/Club/Board/ActivityBoard/ActivityBoard.tsx
  client/src/Components/Club/Board/ActivityBoard/style.ts
  client/src/Components/Club/Board/AwardBoard/AwardBoard.tsx
  client/src/Components/Club/Board/AwardBoard/style.ts
  client/src/Components/Club/Board/ClubBoard.tsx
  client/src/Components/Club/Board/PostBoard/PostBoard.tsx
  client/src/Components/Club/Header/ClubHeader.tsx
  client/src/Components/Club/Header/style.ts
  client/src/Components/Club/Post/ClubPost.tsx
  client/src/Components/Club/Post/Header/PostHeader.tsx
  client/src/Components/Club/Post/Header/style.ts
  client/src/Components/Club/Post/Main/PostMain.tsx
  client/src/Components/Club/Post/Main/style.ts
  client/src/Components/Club/Post/Title/PostTitle.tsx
  client/src/Components/Club/Post/Title/style.ts
  client/src/Components/Club/Post/style.ts
  client/src/Components/Club/Posting/Posting.tsx
  client/src/Components/Club/SideBar/ClubSideBar.tsx
  client/src/Components/Main/MainActivity/MainActivity.tsx
  client/src/Components/Main/MainActivity/style.ts
  client/src/Components/Main/MainAward/MainAward.tsx
  client/src/Components/Main/MainNewClub/MainNewClub.tsx
  client/src/Hooks/useCheckRole.ts
  client/src/Pages/Club/Club.tsx
  client/src/Recoil/User.ts
  client/src/ScroleTop.ts
  client/src/Types/ClubType.ts
  client/src/Types/PostType.ts
  client/src/Types/UserType.ts
  client/src/Util/constant.ts
  client/src/index.tsx
Labels: FE, Feat

#228 Feat/#179 : 로고 수정 및 api 호출 위치 변경
  client/src/Components/Club/Board/ActivityBoard/ActivityBoard.tsx
  client/src/Components/Club/Board/AwardBoard/AwardBoard.tsx
  client/src/Components/Club/Board/InfoBoard/InfoBoard.tsx
  client/src/Components/Club/Main/ClubMain.tsx
  client/src/Components/Club/Main/style.ts
  client/src/Components/Club/SideBar/ClubSideBar.tsx
  client/src/Components/Main/MainAward/style.ts
Labels: FE, Feat

#231 Feat/#179 : 헤더, 게시글, Style 수정
  client/src/Components/Club/Board/PostBoard/PostBoard.tsx
  client/src/Components/Club/Board/PostBoard/style.ts
  client/src/Components/Club/Post/Title/style.ts
  client/src/Components/Header/Header.tsx
  client/src/Components/Header/style.ts
  client/src/Components/Main/MainHeader/style.ts
  client/src/Components/MyPage/MyClub/style.ts
  client/src/Components/MyPage/MyInfo/style.ts
  client/src/Hooks/useCheckRole.ts
  client/src/Recoil/User.ts
  client/src/Types/UserType.ts
Labels: FE, Feat

#232 Feat/#179 - 내정보 수정 및 스타일 수정
  client/src/Components/Club/Board/PostBoard/style.ts
  client/src/Components/Club/Posting/Posting.tsx
  client/src/Components/Club/Posting/style.ts
  client/src/Components/MyPage/MyClub/MyClub.tsx
  client/src/Components/MyPage/MyClub/style.ts
  client/src/Components/MyPage/MyInfo/MyInfo.tsx
  client/src/Components/MyPage/MyInfo/style.ts
Labels: FE, Feat
