Repository taehong0-0/Ucluverse, pull requests merged in 2022-03, with the labels that each got.

#11 Fix/#9: 트랜잭션 적용
  server/package-lock.json
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/main.ts
  server/src/user/user.service.ts
Labels: BE, Fix

#13 Feat/#12 : 리프레시 토큰 DB 저장 시 암호화
  server/package-lock.json
  server/package.json
  server/src/user/user.service.ts
Labels: BE, Feat

#20 Refactor/#6 : JWT 토큰 관련 쿠키 속성 설정
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: BE, Refactor

#22 Refactor/#21 signup시 학과 정보 입력
  server/src/departments/departments.controller.spec.ts
  server/src/departments/departments.controller.ts
  server/src/departments/departments.module.ts
  server/src/departments/departments.service.spec.ts
  server/src/departments/departments.service.ts
  server/src/departments/entities/department.entity.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/entities/user.entity.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: BE, Refactor

#35 Feat/#31 메인페이지 부분 헤더 컴포넌트 구현
  client/src/Assets/검색아이콘.svg
  client/src/Assets/검색창.svg
  client/src/Assets/메인헤더.png
  client/src/Assets/메인헤더글.svg
  client/src/Components/Header/style.ts
  client/src/Components/Main/MainHeader/MainHeader.tsx
  client/src/Components/Main/MainHeader/SearchBar.tsx
  client/src/Components/Main/MainHeader/style.ts
  client/src/Pages/Main/Main.tsx
Labels: FE, Feat

#38 Feat/#32
  client/src/Assets/FAQ.png
  client/src/Assets/공지사항.png
  client/src/Assets/인기게시판.png
  client/src/Components/Main/MainBoard/MainBoard.tsx
  client/src/Components/Main/MainBoard/MainBoardContainer.tsx
  client/src/Components/Main/MainBoard/style.ts
  client/src/Components/Main/MainHeader/style.ts
  client/src/Pages/Main/Main.tsx
Labels: FE, Feat

#39 Feat/#31 : Style - 헤더 스타일 변경
  client/src/Components/Main/MainHeader/MainHeader.tsx
  client/src/Components/Main/MainHeader/style.ts
Labels: FE, Feat
